services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - ENV=${ENV:-dev}
    command: npx playwright test
    volumes:
      - ./playwright-report/:/practiceapp/playwright-report
      - ./test-results/:/practiceapp/test-results