name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:
    inputs:
      target_env:
        description: 'choose env'
        required: true
        default: 'staging'
        type: choice
        options:
          - dev
          - staging
      test_suite:
        description: 'Choose Test Suite'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      ENV: ${{ github.event.inputs.target_env || 'staging'}}

    steps:
    - uses: actions/checkout@v4

    - name: Determine Test Suite Tag
      id: set-tag
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "GREP_TAG=@sanity" >> $GITHUB_ENV
        elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "GREP_TAG=@${{ github.event.inputs.test_suite }}" >> $GITHUB_ENV
        else
          echo "GREP_TAG=@smoke" >> $GITHUB_ENV
        fi

    # 1. creat Docker image
    - name: Build Docker image
      run: docker build -t my-practice-app .

    # 2. run test on container
    - name: Run Playwright tests in Docker
      env:
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      run: |
        docker run --rm \
          -e ENV="${ENV}" \
          -e TEST_EMAIL="${TEST_EMAIL}" \
          -e TEST_PASSWORD="${TEST_PASSWORD}" \
          -v ${{ github.workspace }}/playwright-report:/practiceapp/playwright-report \
          my-practice-app npx playwright test --grep "${GREP_TAG}"

    # 3. test report upload
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30